Add support for QueueLimit, fixes #36
serilog-contrib/serilog-sinks-slack pull request #37
Opened 2022-01-29 14:02 UTC by BrightSoul

2022-01-31 07:04 UTC, TrapperHell requested changes
Adjust optional-param ordering, avoid redefining default queue-limit value

2022-01-31 07:04 UTC, TrapperHell commented on Serilog.Sinks.Slack/SlackSink.cs
> +            : base(options.BatchSizeLimit, options.Period, options.QueueLimit ?? PeriodicBatchingSink.NoQueueLimit)
Using `PeriodicBatchingSink.NoQueueLimit` seems to translate into an actual no-limit, rather than the default 10k. It might be best to construct a `PeriodicBatchingSinkOptions` yourself to pass to the base constructor, since passing nullable-int is not allowed, and omitting the param seems to [override](https://github.com/serilog/serilog-sinks-periodicbatching/blob/db4250fa7706ebec56fb89055e6b6bf85c7df762/src/Serilog.Sinks.PeriodicBatching/Sinks/PeriodicBatching/PeriodicBatchingSink.cs#L87) the default 10k value with null.

2022-02-13 16:38 UTC, BrightSoul commented on Serilog.Sinks.Slack/SlackSink.cs
> +            : base(options.BatchSizeLimit, options.Period, options.QueueLimit ?? PeriodicBatchingSink.NoQueueLimit)
Unfortunately, the constructor accepting a `PeriodicBatchingSinkOptions` [is private](https://github.com/serilog/serilog-sinks-periodicbatching/blob/db4250fa7706ebec56fb89055e6b6bf85c7df762/src/Serilog.Sinks.PeriodicBatching/Sinks/PeriodicBatching/PeriodicBatchingSink.cs#L115).

I could use this other [public constructor](https://github.com/serilog/serilog-sinks-periodicbatching/blob/db4250fa7706ebec56fb89055e6b6bf85c7df762/src/Serilog.Sinks.PeriodicBatching/Sinks/PeriodicBatching/PeriodicBatchingSink.cs#L66-L70) but that's also accepting a `IPeriodicBatchedSink`. Using it would mean following [their direction](https://github.com/serilog/serilog-sinks-periodicbatching/blob/db4250fa7706ebec56fb89055e6b6bf85c7df762/src/Serilog.Sinks.PeriodicBatching/Sinks/PeriodicBatching/PeriodicBatchingSink.cs#L42)...

> Implement `IBatchedLogEventSink` and use the `PeriodicBatchingSinkOptions` constructor.

...which would have to be done anyway sometime in the future since the current approach of deriving `PeriodicBatchingSink` has been marked `Obsolete`.
This, of course, requires more work so I'll send a separate pull request for this.

2022-02-13 16:38 UTC, BrightSoul commented on Serilog.Sinks.Slack/SlackLoggerConfigurationExtensions.cs
> +            int? queueLimit = 100000,
I moved the optional parameter to the end but I could not set the default value to null (see my comment on last conversation).

2022-02-13 16:38 UTC, BrightSoul commented on Serilog.Sinks.Slack/SlackLoggerConfigurationExtensions.cs
> +            int? queueLimit = 100000,
I moved the optional parameter to the end but I could not set the default value to null (see my comment on last conversation).

2022-02-13 17:52 UTC, BrightSoul commented on Serilog.Sinks.Slack/SlackSink.cs
> +            : base(options.BatchSizeLimit, options.Period, options.QueueLimit ?? PeriodicBatchingSink.NoQueueLimit)
Opened PR #38, which is using the constructor accepting the `PeriodicBatchingSinkOptions`. Still, I think the default value for `QueueLimit` should not be `null` because `null` is already used to indicate a limitless queue.

2022-02-15 15:19 UTC, merged