Using property CustomSlackChannel from logEvent as channel name override
serilog-contrib/serilog-sinks-slack pull request #44
Opened 2023-08-03 09:15 UTC by seirysjs

If such property exists in `logEvent` properties, then use it as slack channel name instead.

2023-08-03 10:08 UTC, NerijusD commented
@mgibas Hello, that is needed feature. Who could review and merge this?

2023-08-03 10:12 UTC, seirysjs commented
This also allows scoped Logs to override channel name
for example:
```
using (_logger.BeginScope("{CustomSlackChannel}", customSlackChannel))
{
    _logger.LogCritical(exceptionToLog, message, args);
}
```

2023-08-03 10:18 UTC, seirysjs commented
Please review this, it's highly required feature 
@augustoproiete @bartelink @khellang

2023-08-03 10:23 UTC, bartelink commented on Serilog.Sinks.Slack/SlackSink.cs
> +                    Channel = logEvent.Properties.ContainsKey("CustomSlackChannel") ? logEvent.Properties["CustomSlackChannel"].ToString().Replace("\"", string.Empty) : _options.CustomChannel,
TryGetValue and a pattern match?

2023-08-03 10:34 UTC, seirysjs commented on Serilog.Sinks.Slack/SlackSink.cs
> +                    Channel = logEvent.Properties.ContainsKey("CustomSlackChannel") ? logEvent.Properties["CustomSlackChannel"].ToString().Replace("\"", string.Empty) : _options.CustomChannel,
@bartelink changed to use `TryGetValue` with `pattern matching`. Would this be acceptable? if not, please could you provide an example what you have in mind exactly?

2023-08-03 11:14 UTC, bartelink commented on Serilog.Sinks.Slack/SlackSink.cs
> +                    Channel = logEvent.Properties.ContainsKey("CustomSlackChannel") ? logEvent.Properties["CustomSlackChannel"].ToString().Replace("\"", string.Empty) : _options.CustomChannel,
Looks better to me now 👍 

NOTE I'm not a repo owner/maintainer and don't have much insight into the ground rules/usage of the sink, so unfortunately I'm no use to you in getting to your overall goal...

2023-08-03 11:24 UTC, seirysjs commented on Serilog.Sinks.Slack/SlackSink.cs
> +                    Channel = logEvent.Properties.ContainsKey("CustomSlackChannel") ? logEvent.Properties["CustomSlackChannel"].ToString().Replace("\"", string.Empty) : _options.CustomChannel,
thanks for your input in reviewing this

2023-08-03 11:29 UTC, seirysjs commented on Serilog.Sinks.Slack/SlackSink.cs
> +                    Channel = logEvent.Properties.ContainsKey("CustomSlackChannel") ? logEvent.Properties["CustomSlackChannel"].ToString().Replace("\"", string.Empty) : _options.CustomChannel,
@bartelink could you please tell me who are the maintainers of this repo? and who is owner? so i could tag them to merge this

2023-08-03 11:51 UTC, bartelink commented on Serilog.Sinks.Slack/SlackSink.cs
> +                    Channel = logEvent.Properties.ContainsKey("CustomSlackChannel") ? logEvent.Properties["CustomSlackChannel"].ToString().Replace("\"", string.Empty) : _options.CustomChannel,
No idea; in general I'd avoid atting people and let them get notified; people have day jobs...

2023-08-03 11:55 UTC, seirysjs commented on Serilog.Sinks.Slack/SlackSink.cs
> +                    Channel = logEvent.Properties.ContainsKey("CustomSlackChannel") ? logEvent.Properties["CustomSlackChannel"].ToString().Replace("\"", string.Empty) : _options.CustomChannel,
Well, thanks for your time. I apologize for disturbing your working hours

2023-08-03 12:26 UTC, bartelink commented on Serilog.Sinks.Slack/SlackSink.cs
> +                    Channel = logEvent.Properties.ContainsKey("CustomSlackChannel") ? logEvent.Properties["CustomSlackChannel"].ToString().Replace("\"", string.Empty) : _options.CustomChannel,
I personally don't happen to mind atm (I'm doing a mishmash of stuff including lots of public github stuff today).

But for anyone who created a sink, brought it to the world, and maybe moved to a company with a different log rig, seeing a message in your inbox from an @ 20 mins after an issue is created might provoke a "Oh noes, I owe the internet stuff!"

2023-08-03 12:37 UTC, seirysjs commented on Serilog.Sinks.Slack/SlackSink.cs
> +                    Channel = logEvent.Properties.ContainsKey("CustomSlackChannel") ? logEvent.Properties["CustomSlackChannel"].ToString().Replace("\"", string.Empty) : _options.CustomChannel,
I will keep that in mind 👍

2023-08-04 07:16 UTC, TrapperHell commented
Hi @seirysjs, thank you for your contribution.

As bartelink pointed out, please allow a reasonable amount of time before pinging to get something done. We all have jobs and work to do.

While using this library myself I have had a use-case to get the logger to write to different channels - and I got it done without resorting to this. 

I will consider your approach and try to balance the easiness which it adds versus any potential pitfalls / feature-bloating. I will keep you posted.

2023-08-04 07:17 UTC, TrapperHell commented on README.md
> +Scope overriden channel name:
Typo in `overriden`. Should be `overridden`.

2023-08-04 07:40 UTC, NerijusD commented
> Hi @seirysjs, thank you for your contribution.
> 
> As bartelink pointed out, please allow a reasonable amount of time before pinging to get something done. We all have jobs and work to do.
> 
> While using this library myself I have had a use-case to get the logger to write to different channels - and I got it done without resorting to this.
> 
> I will consider your approach and try to balance the easiness which it adds versus any potential pitfalls / feature-bloating. I will keep you posted.

@TrapperHell Could you share your approach, how did you do it? Did you have predefined channels? In our use case we want to have dynamic channel names on each run for our application.

2023-08-04 09:35 UTC, seirysjs commented on README.md
> +Scope overriden channel name:
typo fixed

2023-08-04 09:38 UTC, seirysjs commented
> Hi @seirysjs, thank you for your contribution.
> 
> As bartelink pointed out, please allow a reasonable amount of time before pinging to get something done. We all have jobs and work to do.
> 
> While using this library myself I have had a use-case to get the logger to write to different channels - and I got it done without resorting to this.
> 
> I will consider your approach and try to balance the easiness which it adds versus any potential pitfalls / feature-bloating. I will keep you posted.

Thank you for your review and insight. I will do my best to not tag people like this in the future anymore. I'm sorry for the disturbance in regards to this PR.

Please do share your approach to have the logger to write to different channels. I would really appreciate it!

2023-08-04 16:05 UTC, TrapperHell commented
As requested, here is the approach that I have used to cater for my need. However please note that this does not support dynamic, runtime slack channel changes.

> Did you have predefined channels? In our use case we want to have dynamic channel names on each run for our application.

Yes, the channels were predefined.

The approach is as follows, and powered by the [Serilog Expressions](https://github.com/serilog/serilog-expressions) library:

Define a logger per channel that you intend to log to, you can do this in the JSON configuration itself, such as:

```json
{
  "Name": "Logger",
  "Args": {
    "configureLogger": {
      "Filter": [
        {
          "Name": "ByIncludingOnly",
          "Args": {
            "expression": "EventId.Id = 1"
          }
        }
      ],
      "WriteTo": [
        {
          "Name": "Slack",
          "Args": { "Configure Slack sink configuration here..." }
        }
      ]
    }
  }
},
{
  ... More loggers here...
}
```

and then to log you would simply use:

```csharp
logger.LogInformation(new EventId(1), "Greetings...");
```

In reality I used another function to resolve the EventId necessary for which message, since it wasn't really dependent on log severity but business-logic.

I will review your changes during this weekend and let you know. Overall it looks fine, however I'm hoping there's a somewhat better options than using `.Replace("\"", string.Empty)` , and I might be a little pedantic here, but perhaps call the parameter `{ChannelOverride}` instead of `{CustomSlackChannel}`

2023-08-07 10:13 UTC, seirysjs commented
PR updated with solution to `ShowPropertyAttachments` exposing properties that are ment to be used as config overrides.
Added overrides for `CustomUserName` and `CustomIcon` as well. Renamed the property  `CustomSlackChannel` to `CustomChannel`. 
Reusing `SlackSinkOptions` property names that are meant to be overridden.
To override the config properties, it's now necessary to specify them in `PropertyOverrideList` that was newly added to `SlackSinkOptions`.

2023-08-07 10:51 UTC, NerijusD requested changes

2023-08-07 10:51 UTC, NerijusD commented on Serilog.Sinks.Slack/Models/SlackSinkOptions.cs
> +        public List<OverridableProperties> PropertyOverrideList { get; set; }
Could this be `HashSet` instead of a `List`?

2023-08-07 10:51 UTC, NerijusD commented on Serilog.Sinks.Slack/SlackSink.cs
> +        private string GetPropertyFromException(LogEvent logEvent, OverridableProperties overridableProperty, string defaultValue)
Could this be named differently? This method name looks strange. Why it has part `FromException` ?

2023-08-08 05:32 UTC, seirysjs commented on Serilog.Sinks.Slack/Models/SlackSinkOptions.cs
> +        public List<OverridableProperties> PropertyOverrideList { get; set; }
changed to `HashSet`

2023-08-08 05:32 UTC, seirysjs commented on Serilog.Sinks.Slack/SlackSink.cs
> +        private string GetPropertyFromException(LogEvent logEvent, OverridableProperties overridableProperty, string defaultValue)
Renamed to `GetPropertyFromLogEvent`.

2023-08-09 07:21 UTC, NerijusD commented
@TrapperHell will you be able to give another look at this at some point this week?

2023-08-09 10:28 UTC, seirysjs commented
@TrapperHell changed version from `2.2.1` to `2.2.2`

2023-08-09 10:29 UTC, TrapperHell approved these changes

2023-08-09 10:29 UTC, merged

2023-08-09 10:34 UTC, TrapperHell commented
We need your help with this one @mgibas. The NuGet push failed - seems like the API key has expired or is no longer valid.

2023-08-14 05:52 UTC, NerijusD commented
Hello @TrapperHell, @mgibas,

Any updates on publishing new package?

2023-08-14 10:54 UTC, mgibas commented
@TrapperHell token regenerated - see ya next year!